
CREATE TABLE PRODUCT (
	PRODUCT_ID 					INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_ID 				INT,
	BARCODE 					VARCHAR2(100),
	PRODUCT_NAME	 			VARCHAR2(100),
	PRODUCT_MENU_NAME 			VARCHAR2(100),
	DESCR						VARCHAR2(200),
	INVENTORY_ON_HAND 			NUMBER(10,0),
	SAFETY_INVENTORY_ON_HAND 	NUMBER(10,0),
	UNIT_PRICE 					NUMBER(10,2),
	TAXABLE1					VARCHAR2(1),
	TAXABLE2					VARCHAR2(1),
	TAXABLE3					VARCHAR2(1),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID 				INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_NAME				VARCHAR2(100),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID 				INT NOT NULL AUTO_INCREMENT,
	EMPLOYEE_NAME				VARCHAR2(50),
	EMAIL_ADDRESS				VARCHAR2(100),
	PHONE_NUMBER				VARCHAR2(50),
	PIN							VARCHAR2(20),
	EMPLOYEE_LEVEL				VARCHAR2(50),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE CART (
	CART_ID		 				INT NOT NULL AUTO_INCREMENT,
	CASHIER_ID					INT,
	CUSTOMER_ID					INT,
	ORDER_DTM					DATETIME,
	QUANTITY_TOTAL				INT,
	ORDER_SUB_TOTAL				NUMBER(10,2),
	ORDER_TAX1_TOTAL			NUMBER(10,2),
	ORDER_TAX2_TOTAL			NUMBER(10,2),
	ORDER_TAX3_TOTAL			NUMBER(10,2),
	ORDER_TAX_TOTAL				NUMBER(10,2),
	ORDER_GRAND_TOTAL			NUMBER(10,2),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (CART_ID)
);

CREATE TABLE CART_ITEM (
	CART_ITEM_ID 				INT NOT NULL AUTO_INCREMENT,
	CART_ID						INT,
	PRODUCT_ID					INT,
	LINE_NUMBER					INT,
	EMPLOYEE_ID					INT,
	ORDER_DTM					DATETIME,
	QUANTITY					INT,
	PRODUCT_NAME				VARCHAR2(100),
	UNIT_PRICE 					NUMBER(10,2),
	ITEM_SUB_TOTAL				NUMBER(10,2),
	ITEM_TAX1_TOTAL				NUMBER(10,2),
	ITEM_TAX2_TOTAL				NUMBER(10,2),
	ITEM_TAX3_TOTAL				NUMBER(10,2),
	ITEM_TAX_TOTAL				NUMBER(10,2),
	ITEM_GRAND_TOTAL			NUMBER(10,2),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (CART_ITEM_ID)
);

