CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID 				INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_NAME				VARCHAR2(100),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE PRODUCT (
	PRODUCT_ID 					INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_ID 				INT,
	BARCODE 					VARCHAR2(100),
	PRODUCT_NAME	 			VARCHAR2(100),
	UNIT_PRICE 					NUMBER(10,2),
	TAXABLE_1_FLG				VARCHAR2(1),
	TAXABLE_2_FLG				VARCHAR2(1),
	TAXABLE_3_FLG				VARCHAR2(1),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID 				INT NOT NULL AUTO_INCREMENT,
	EMPLOYEE_NAME				VARCHAR2(50),
	EMAIL_ADDRESS				VARCHAR2(100),
	PHONE_NUMBER				VARCHAR2(50),
	PIN							VARCHAR2(20),
	EMPLOYEE_LEVEL				VARCHAR2(50),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID 				INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_NAME				VARCHAR2(50),
	EMAIL_ADDRESS				VARCHAR2(100),
	PHONE_NUMBER				VARCHAR2(50),
	MEMO						VARCHAR2(20),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE TICKET (
	TICKET_ID	 				INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_ID					INT,
	TICKET_DTM					DATETIME,
	QTY_TOTAL					INT,
	SUBTOTAL_AMT				NUMBER(10,2),
	TAX1_RATE					NUMBER(10,2),
	TAX1_TOTAL_AMT				NUMBER(10,2),
	TAX2_RATE					NUMBER(10,2),
	TAX2_TOTAL_AMT				NUMBER(10,2),
	TAX3_RATE					NUMBER(10,2),
	TAX3_TOTAL_AMT				NUMBER(10,2),
	TAX_TOTAL_AMT				NUMBER(10,2),
	TOTAL_AMT					NUMBER(10,2),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (TICKET_ID)
);

CREATE TABLE TICKET_DATA (
	TICKET_DATA_ID				INT NOT NULL AUTO_INCREMENT,
	TICKET_ID	 				INT,
	PRODUCT_ID	 				INT,
	QTY			 				INT,
	UNIT_PRICE 					NUMBER(10,2),
	TOTAL_SALES_AMT 			NUMBER(10,2),
	TAXABLE_1_FLG				VARCHAR2(1),
	TAXABLE_2_FLG				VARCHAR2(1),
	TAXABLE_3_FLG				VARCHAR2(1),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (TICKET_DATA_ID)
);

CREATE TABLE PAYMENT (
	PAYMENT_ID					INT NOT NULL AUTO_INCREMENT,
	TICKET_ID	 				INT,
	PRODUCT_ID	 				INT,
	PAYMENT_METHOD				VARCHAR2(20),
	PAYMENT_AMT 				NUMBER(10,2),
	REMAINING_BALANCE_DUE_AMT 	NUMBER(10,2),
	TENDER_AMT 					NUMBER(10,2),
	CHANGE_AMT 					NUMBER(10,2),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE CONFIG (
	CONFIG_ID					INT NOT NULL AUTO_INCREMENT,
	CONFIG_CATEGORY				VARCHAR2(20),
	CONFIG_NAME					VARCHAR2(20),
	CONFIG_VALUE				VARCHAR2(20),
	STATUS						VARCHAR2(20),
	CREATED_DTM					DATETIME,
	CREATED_BY					INT,
	UPDATED_DTM					DATETIME,
	UPDATED_BY					INT,
	PRIMARY KEY (CONFIG_ID)
);


