
CREATE TABLE PRODUCT (
	PRODUCT_ID 					INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_ID 				INT,
	BARCODE 					VARCHAR2(100),
	FULL_NAME 					VARCHAR2(100),
	SHORT_NAME_ENG 				VARCHAR2(100),
	SHORT_NAME_OTHER 			VARCHAR2(100),
	INVENTORY_ON_HAND 			NUMBER(10,0),
	SAFETY_INVENTORY_ON_HAND 	NUMBER(10,0),
	COST_AMT 					NUMBER(10,2),
	SALES_AMT 					NUMBER(10,2),
	STATUS						VARCHAR2(20),
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DEPARTMENT (
	DEPARTMENT_ID 				INT NOT NULL AUTO_INCREMENT,
	DEPARTMENT_NAME				VARCHAR2(100),
	STATUS						VARCHAR2(20),
	PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID 				INT NOT NULL AUTO_INCREMENT,
	EMPLOYEE_NAME				VARCHAR2(50),
	EMAIL_ADDRESS				VARCHAR2(100),
	PHONE_NUMBER				VARCHAR2(50),
	PIN							VARCHAR2(20),
	EMPLOYEE_LEVEL				VARCHAR2(50),
	STATUS						VARCHAR2(20),
	PRIMARY KEY (EMPLOYEE_ID)
);