INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, PIN, STATUS) VALUES (1, 'ADMIN', '0000', 'ACTIVE');

INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE) VALUES ('111', 'Monitor', 199.99);
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE) VALUES ('222', 'Mouse', 29.99);
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE) VALUES ('333', 'Keyboard', 15.50);