INSERT INTO EMPLOYEE (EMPLOYEE_NAME, PIN, STATUS) VALUES ('ADMIN', '0000', 'ACTIVE');

INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('1', 'Monitor', 199.99, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('2', 'Mouse', 29.99, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('3', 'Keyboard', 15.50, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('4', 'Speaker', 79.99, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('5', 'Pen', 2.39, 'Y', 'N', 'N');

INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX1_RATE', '0.06');
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX2_RATE', null);
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX3_RATE', null);

INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('APPLICATION', 'SCREEN_WIDTH', '1920');
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('APPLICATION', 'SCREEN_HEIGHT', '1080');