INSERT INTO EMPLOYEE (EMPLOYEE_NAME, PIN, STATUS) VALUES ('ADMIN', '0000', 'ACTIVE');

INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('111', 'Monitor', 199.99, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('222', 'Mouse', 29.99, 'Y', 'N', 'N');
INSERT INTO PRODUCT (BARCODE, PRODUCT_NAME, UNIT_PRICE, TAXABLE_1_FLG, TAXABLE_2_FLG, TAXABLE_3_FLG) VALUES ('333', 'Keyboard', 15.50, 'Y', 'N', 'N');

INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX1_RATE', '0.06');
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX2_RATE', null);
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('TAX', 'TAX3_RATE', null);

INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('APPLICATION', 'SCREEN_WIDTH', '1366');
INSERT INTO CONFIG (CONFIG_CATEGORY, CONFIG_NAME, CONFIG_VALUE) VALUES ('APPLICATION', 'SCREEN_HEIGHT', '768');